// presentation/react-ui/src/features/posts/components/molecules/PostListItem.tsx
import { Favorite, Share } from "@mui/icons-material"
import { Card, CardActions, CardContent, CardHeader, IconButton, Typography } from "@mui/material"
import { PostModel } from "@tech-talk/core"
import UserAvatar from "../../../users/components/atoms/UserAvatar"

const PostListItem = ({ post, initials}: PostListItemProps) => <Card key={post.Id} sx={{ borderBottom: 'solid 1px #ddd', padding: '13px 0' }}>
	<CardHeader 
		avatar={<UserAvatar {...{initials}} />}
		title={post.Title}
		sx={{ '& .MuiCardHeader-title': { textTransform: 'capitalize' } }}
	/>
	<CardContent>
		<Typography variant="body2" color="text.secondary">
			{post.Body}
		</Typography>
	</CardContent>
	<CardActions>
		<IconButton>
			<Favorite />
		</IconButton>
		<IconButton>
			<Share />
		</IconButton>
	</CardActions>
</Card>

export default PostListItem

interface PostListItemProps {
	post: PostModel
	initials: string
}

// presentation/vue-ui/src/features/posts/components/molecules/PostListItem.vue
<template>
	<v-card
		class="post-list__item"
		elevation="13"
		:title="post.Title">
		<template v-slot:prepend>
			<UserAvatar :initials="initials" />
		</template>
		<v-card-text>
			{{ post.Body }}
		</v-card-text>
		<v-card-actions>
			<v-spacer></v-spacer>
			<v-btn
				color="medium-emphasis"
				icon="mdi-bookmark"
				size="small"></v-btn>
			<v-btn
				color="medium-emphasis"
				icon="mdi-share-variant"
				size="small"></v-btn>
		</v-card-actions>
	</v-card>
</template>

<script lang="ts">
import { UserAvatar } from '@/features/users';
import type { PostModel } from '@tech-talk/core';
import { defineComponent, type PropType } from 'vue';

export default defineComponent({
	name: 'PostListItem',
	components: { UserAvatar },
	props: {
		post: {
			type: Object as PropType<PostModel>,
			required: true
		},
		initials: {
			type: String,
			default: null
		}
	}
})
</script>
