// presentation/angular-ui/src/app/features/posts/components/organisms/posts-list/posts-list.component.ts
import { Component, EventEmitter, Input, OnChanges, OnDestroy, OnInit, Output } from '@angular/core';
import { ApiStatus, ICommonState, PostModel, UserModel } from '@tech-talk/core';
import { PostService } from '../../../services/PostService';

/**
 * 
 */
@Component({
	selector: 'app-posts-list',
	templateUrl: 'posts-list.component.html',
	styleUrl: 'posts-list.component.scss',
})
export class PostsListComponent implements OnInit, OnChanges, OnDestroy {
	/**
	 * 
	 */
	@Input() user: UserModel | null = null

	/**
	 * 
	 */
	@Output() back = new EventEmitter<void>()

	/**
	 * 
	 */
	public posts: PostModel[] = []

	/**
	 * 
	 */
	public status: ApiStatus = 'idle'

	/**
	 * 
	 * @param service 
	 */
	constructor(private service: PostService) { }
	
	/**
	 * 
	 */
	ngOnInit(): void {
		this.service.store.collection$.subscribe((state: ICommonState<PostModel[]>) => {
			this.posts = [...(state.data || [])]
			this.status = state.status
		})
	}

	/**
	 * 
	 */
	ngOnChanges(): void {
		if (this.user === null) 
			return
		this.service.getPostsByUser(this.user)
	}

	/**
	 * 
	 */
	ngOnDestroy(): void {
		this.service.store.unsubscribeAll()
	}

	/**
	 * 
	 */
	public onBack(): void {
		this.back.emit()
	}
}
<div class="posts-list">
	<button mat-icon-button (click)="onBack()">
        <mat-icon>arrow_back</mat-icon>
	</button>
	<div *ngIf="status === 'succeeded'">
		<mat-card apperance="outlined" *ngFor="let post of posts">
			<mat-card-header>
				<app-user-avatar mat-card-avatar [name]="user?.Name!"></app-user-avatar>
				<mat-card-title>
					{{post.Title}}
				</mat-card-title>
			</mat-card-header>
			<mat-card-content>
				{{post.Body}}
			</mat-card-content>
			<mat-card-actions align="end">
				<button mat-icon-button>
					<mat-icon>chat</mat-icon>
				</button>
				<button mat-icon-button>
					<mat-icon>favorite</mat-icon>
				</button>
			</mat-card-actions>
		</mat-card>
	</div>
	<app-posts-list-skeleton *ngIf="status === 'pending'" />
	<app-error-state *ngIf="status === 'rejected'" />
</div>

// presentation/vue-ui/src/features/posts/components/organisms/PostsList.vue
<template>	
	<div class="posts-list">
		<v-btn icon="mdi-arrow-left" @click="onBack"></v-btn>
		<div class="posts-list__container">
			<PostListItem v-for="post in posts" 
				:key="post.Id"
				:post="post"
				:initials="user?.Initials" />
			<PostsListSkeleton v-if="status === 'pending'" />
		</div>
	</div>
</template>

<script lang="ts">
import type {
	ApiStatus,
	ICommonState,
	PostModel,
	UserModel
} from '@tech-talk/core';
import {
	defineComponent,
	onBeforeUnmount,
	onMounted,
	type PropType,
	ref,
	watch
} from 'vue';
import { usePostQueries } from '../../services/usePostQueries';
import PostListItem from '../molecules/PostListItem.vue';
import PostsListSkeleton from '../molecules/PostsListSkeleton.vue';

export default defineComponent({
	name: 'PostsList',
	emits: [ 'navigation-back' ],
	components: { PostListItem, PostsListSkeleton },
	props: {
		user: {
			type: Object as PropType<UserModel | null>,
			default: null
		},
		
	},
	setup(props, { emit }) {
		const posts = ref<PostModel[]>([])
		const status = ref<ApiStatus>('idle')
		const { store, getPostsByUser } = usePostQueries()

		const fetchPosts = () => {
			if (props.user) {
				getPostsByUser(props.user);
			}
		}

		onMounted(() => {
			store.collection$.subscribe((state: ICommonState<PostModel[]>) => {
				posts.value = state.data || [];
				status.value = state.status;
			})
			fetchPosts()
		})

		watch(() => props.user, fetchPosts)

		onBeforeUnmount(() => {
			store.unsubscribeAll()
		})

		const onBack = () => {
			emit('navigation-back')
		}

		return {
			posts,
			status,
			onBack,
		}
	}
})
</script>

<style scoped>

.posts-list__container {
	padding: 8px;
}

.post-list__item {
	margin-bottom: 13px;
}

.v-card-title {
	text-transform: capitalize !important;
}
</style>
